import CommonLayout from "../layout";
import Toast from "@/components/CustomizedSnackbars";
import Box from '@mui/material/Box';
import Stack from '@mui/material/Stack';
import AppNavbar from './components/AppNavbar';
import Header from './components/Header';
import SideMenu from './components/SideMenu';

export const metadata = {
  title: "Dandori - Autentificacion",
  description: "Dandori - Autentificacion",
};

export default function AuthLayout({ children }) {
  return (
    <CommonLayout>
      {<Box sx={{ display: 'flex' }}>
        <SideMenu />
        <AppNavbar />
        <Box
          component="main"
          sx={{
            flexGrow: 1,
            overflow: 'auto',
          }}
        >
          <Stack
            spacing={2}
            sx={{
              alignItems: 'center',
              mx: 3,
              pb: 5,
              mt: { xs: 8, md: 0 },
            }}
          >
            <Header />
            {children}
          </Stack>
        </Box>
      </Box>}
      <Toast/>
    </CommonLayout>
  );
}




// import { Geist, Geist_Mono } from "next/font/google";
// import CssBaseline from '@mui/material/CssBaseline';

// import AppTheme from './shared-theme/AppTheme';

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body>
//         <main className={`${geistSans.variable} ${geistMono.variable}`}>
//           {/* <AppTheme> */}
//             {/* <CssBaseline enableColorScheme /> */}
//             <Box sx={{ display: 'flex' }}>
//               <SideMenu />
//               <AppNavbar />
//               <Box
//                 component="main"
//                 sx={{
//                   flexGrow: 1,
//                   overflow: 'auto',
//                 }}
//               >
//                 <Stack
//                   spacing={2}
//                   sx={{
//                     alignItems: 'center',
//                     mx: 3,
//                     pb: 5,
//                     mt: { xs: 8, md: 0 },
//                   }}
//                 >
//                   <Header />
//                   {children}
//                 </Stack>
//               </Box>
//             </Box>
//           {/* </AppTheme> */}
//         </main>
//       </body>
//     </html>
//   );
// }
